/* eslint-disable prettier/prettier */
const allCountries = { 
    AF: 'Afeganistão',
    AX: 'Ilhas Åland',
    AL: 'Albânia',
    DZ: 'Argélia',
    AS: 'Samoa Americana',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antárctica',
    AG: 'Antigua e Barbuda',
    AR: 'Argentina',
    AM: 'Armênia',
    AW: 'Aruba',
    AU: 'Austrália',
    AT: 'Áustria',
    AZ: 'Azerbaijão',
    BS: 'Bahamas',
    BH: 'Bahrein',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Bielorrússia',
    BE: 'Bélgica',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Butão',
    BO: 'Bolívia',
    BA: 'Bósnia e Herzegovina',
    BW: 'Botsuana',
    BV: 'Ilha Bouvet',
    BR: 'Brasil',
    IO: 'Território do Oceano Índico Britânico',
    BN: 'Brunei',
    BG: 'Bulgária',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambódia',
    CM: 'Camarões',
    CA: 'Canadá',
    CV: 'Cabo Verde',
    KY: 'Ilhas Caiman',
    CF: 'República Centro-Africana',
    TD: 'Chade',
    CL: 'Chile',
    CN: 'China',
    CX: 'Ilha Christma',
    CC: 'Ilhas Cocos (Keeling)',
    CO: 'Colômbia',
    KM: 'Comores',
    CG: 'Congo',
    CD: 'Congo, República Democrática',
    CK: 'Ilhas Cook',
    CR: 'Costa Rica',
    CI: 'Costa do Marfim',
    HR: 'Croácia',
    CU: 'Cuba',
    CY: 'Chipre',
    CZ: 'Tchéquia',
    DK: 'Dimamarca',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'República Dominicana',
    EC: 'Equador',
    EG: 'Egito',
    SV: 'El Salvador',
    GQ: 'Guiné Equatorial',
    ER: 'Eritreia',
    EE: 'Estônia',
    ET: 'Etiópia',
    FK: 'Ilhas Falklan (Malvinas)',
    FO: 'Ilhas Faroé',
    FJ: 'Fiji',
    FI: 'Finlândia',
    FR: 'França',
    GF: 'Guiana Francesa',
    PF: 'Polynésia Francesa',
    TF: 'Terras Austrais e Antárticas Francesas',
    GA: 'Gabão',
    GM: 'Gâmbia',
    GE: 'Geórgia',
    DE: 'Alemanha',
    GH: 'Gana',
    GI: 'Gibraltar',
    GR: 'Grécia',
    GL: 'Groenlândia',
    GD: 'Granada',
    GP: 'Guadelupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guiné',
    GW: 'Guiné-Bissau',
    GY: 'Guiana',
    HT: 'Haiti',
    HM: 'Ilha Heard e Ilhas McDonald',
    VA: 'Santa Sé',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungria',
    IS: 'Islândia',
    IN: 'Índia',
    ID: 'Indonésia',
    IR: 'Irã',
    IQ: 'Iraque',
    IE: 'Irlanda',
    IM: 'Ilha de Man',
    IL: 'Israel',
    IT: 'Itália',
    JM: 'Jamaica',
    JP: 'Japão',
    JE: 'Jersey',
    JO: 'Jordânia',
    KZ: 'Cazaquistão',
    KE: 'Quênia',
    KI: 'Quiribati',
    KP: 'Coreia do Norte',
    KR: 'Coreia do Sul',
    XK: 'Kosovo',
    KW: 'Kuwait',
    KG: 'Quirguistão',
    LA: 'Laos',
    LV: 'Letônia',
    LB: 'Líbano',
    LS: 'Lesoto',
    LR: 'Libéria',
    LY: 'Líbia',
    LI: 'Liechtenstein',
    LT: 'Lituânia',
    LU: 'Luxemburgo',
    MO: 'Macau',
    MK: 'Macedónia do Norte',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malásia',
    MV: 'Maldivas',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Ilhas Marshall',
    MQ: 'Martinica',
    MR: 'Mauritânia',
    MU: 'Ilhas Maurício',
    YT: 'Mayotte',
    MX: 'México',
    FM: 'Micronésia',
    MD: 'Moldávia',
    MC: 'Mônaco',
    MN: 'Mongólia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Marrocos',
    MZ: 'Moçambique',
    MM: 'Mianmar',
    NA: 'Namíbia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Países Baixos',
    AN: 'Antilhas Neerlandesas',
    NC: 'Nova Caledônia',
    NZ: 'Nova Zelândia',
    NI: 'Nicarágua',
    NE: 'Níger',
    NG: 'Nigéria',
    NU: 'Niue',
    NF: 'Ilha Norfolg',
    MP: 'Ilhas Marianas do Norte',
    NO: 'Norguega',
    OM: 'Omã',
    PK: 'Paquistão',
    PW: 'Palau',
    PS: 'Territórios Palestinianos',
    PA: 'Panamá',
    PG: 'Papua Nova Guiné',
    PY: 'Paraguai',
    PE: 'Perú',
    PH: 'Filipinas',
    PN: 'Ilhas Pitcairn',
    PL: 'Polônia',
    PT: 'Portugal',
    PR: 'Porto Rico',
    QA: 'Catar',
    RE: 'Ilha da Reunião',
    RO: 'Romênia',
    RU: 'Russia',
    RW: 'Ruanda',
    SH: 'Santa Helena',
    KN: 'São Cristóvão e Névis',
    LC: 'Santa Lúcia',
    PM: 'Saint-Pierre e Miquelon',
    VC: 'São Vicente e Granadinas',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'São Tomé e Príncipe',
    SA: 'Arábia Saudita',
    SN: 'Senegal',
    RS: 'Sérvia',
    SC: 'Seychelles',
    SL: 'Serra Leoa',
    SG: 'Singapura',
    SK: 'Eslováquia',
    SI: 'Eslovênia',
    SB: 'Ilhas Salomão',
    SO: 'Somália',
    ZA: 'África do Sul',
    GS: 'Ilhas Geórgia do Sul e Sandwich do Sul',
    ES: 'Espanha',
    LK: 'Sri Lanka',
    SD: 'Sudão',
    SR: 'Suriname',
    SJ: 'Svalbard e Jan Mayen',
    SZ: 'Swazilândia',
    SE: 'Suécia',
    CH: 'Suiça',
    SY: 'Síria',
    TW: 'Taiwam',
    TJ: 'Tajiquistão',
    TZ: 'Tanzânia',
    TH: 'Tailândia',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad e Tobago',
    TN: 'Tunísia',
    TR: 'Turquia',
    TM: 'Turcomenistão',
    TC: 'Turks e Caicos',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ucrânia',
    AE: 'Emirados Árabes Unidos',
    GB: 'Reino Unido',
    US: 'Estados Unidos',
    UM: 'Ilhas Menores Distantes dos Estados Unidos',
    UY: 'Uruguai',
    UZ: 'Uzbequistão',
    VU: 'Vanuatu',
    VE: 'Venezuela',
    VN: 'Vietnã',
    VG: 'Ilhas Virgens Britânicas',
    VI: 'Ilhas Virgens Americanas',
    WF: 'Wallis e Futuna',
    EH: 'Saara Ocidental',
    YE: 'Iêmen',
    ZM: 'Zâmbia',
    ZW: 'Zimbábue'
}

const countries = Object.keys(allCountries);
const countriesLong = new Map(Object.entries(countries));

module.exports = {
  countries,
  countriesLong,
};